### ISSUE TITLE
nix-shell -A banditSelection produce an error

### ISSUE THREAD

**Issue by xulunfan** [freuk/obps#1]
It produce an error as below. Could you help me fix it?

23:33:04[xlf@master ~/Desktop/obps]$ nix-shell -A banditSelection
error: anonymous function at /home/xlf/Desktop/obps/pkgs/ocs/default.nix:1:1 called without required argument 'ocaml_batteries', at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/customisation.nix:74:12
(use '--show-trace' to show detailed location information)

23:33:38[xlf@master ~/Desktop/obps]$ nix-shell -A banditSelection --show-trace
error: while evaluating the attribute 'buildInputs' of the derivation 'banditSelection' at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'getOutput' at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/attrsets.nix:450:23, called from undefined position:
while evaluating anonymous function at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:97:17, called from undefined position:
while evaluating 'callPackageWith' at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/customisation.nix:113:35, called from /home/xlf/Desktop/obps/default.nix:7:11:
while evaluating 'makeOverridable' at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/customisation.nix:72:24, called from /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/customisation.nix:117:8:
anonymous function at /home/xlf/Desktop/obps/pkgs/ocs/default.nix:1:1 called without required argument 'ocaml_batteries', at /nix/store/idpva9j2lfi353sa1hw9a6nfhby0zkbw-nixpkgs/nixpkgs/lib/customisation.nix:74:12

**Comment by freuk** [comment]
This was due to not pinning [nixpkgs](https://github.com/NixOS/nixpkgs). I added a fix on master, using a pinned 18.03 version. The ocaml_batteries was recently renamed to 'batteries'.

**Comment by xulunfan** [comment]
I used the nixos-18.03, but the system reported a new error.
It looks like about permission, but I can't fix it (even I give it  root permission) .
```
[nix-shell:/home/xlf/Desktop/obps]#  sudo nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz -A banditSelection
these derivations will be built:
  /nix/store/7k9rwh99pc3s6vw2g3q2mskc4ajg1kvr-r-quadprog-1.5-5.drv
  /nix/store/08v6w3pp63r283hck5am6bd49a3zxwzg-r-directlabels-2017.03.31.drv
  /nix/store/yriqpfpjdihlrcqnfi4rxw693d2qjgzn-r-Rcpp-0.12.15.drv
  /nix/store/09nlnf8nnsy85j9qsd13lsriyz78a7hn-r-plyr-1.8.4.drv
  /nix/store/65pwn3bf99gsdcikqb51ynvbp4gd4b3d-r-magrittr-1.5.drv
  /nix/store/cidgacva5fgn7d0pbhmycydh0sgnvx7a-r-glue-1.2.0.drv
  /nix/store/vbkcm7244k59wda8r5grcwvgxgzbpwgy-r-stringi-1.1.6.drv
  /nix/store/2kbb40ncs5cbby6qw9nrdxqhn0icag2g-r-stringr-1.3.0.drv
  /nix/store/0c72fg808h3db4ahv2qvmn5kal5klz4k-r-reshape2-1.4.3.drv
  /nix/store/2zdlqywgpn87ccnnqly1pv9d8c248ycd-r-gtable-0.2.0.drv
  /nix/store/7bgvn11k3jp9gnbl3v5s8rsk37nqqjbk-r-crayon-1.3.4.drv
  /nix/store/h7ygivvhm4kg0bjw042rqak53m88cwk1-r-assertthat-0.2.0.drv
  /nix/store/64rzm0915r8g2wh57jmbj1y2dcxvy8kx-r-cli-1.0.0.drv
  /nix/store/mhwgd5v09avp5hq62p7fvpysayavqjxl-r-utf8-1.1.3.drv
  /nix/store/vilkvz14jsrrq5cb9w852j92lng7rj5d-r-rlang-0.1.6.drv
  /nix/store/j7cs058vxri3xmqcd88wxw5zijy3dcm4-r-pillar-1.1.0.drv
  /nix/store/b5kmil87wfwzbxnjziaj70z3cv7vg83y-r-tibble-1.4.2.drv
  /nix/store/jvnd76y7i6fc311hhgslsim7h1rr2lns-r-lazyeval-0.2.1.drv
  /nix/store/29n85z3yajk7j5c93jkccc93narr218j-r-R6-2.2.2.drv
  /nix/store/9m7lg85smmkvriddvzam31zh80sljkqw-r-viridisLite-0.3.0.drv
  /nix/store/23m0p8pnfh7b01w079h4ih0ll8ysiazg-r-colorspace-1.3-2.drv
  /nix/store/k5vhckksivwh16h4aaknndsm00002crn-r-munsell-0.4.3.drv
  /nix/store/p891d9imgzl4b8hgknv1yziwx0kgaa7z-r-labeling-0.3.drv
  /nix/store/r1smxlzmfc2x6xnadb4wxdlfkm1a6cz2-r-RColorBrewer-1.1-2.drv
  /nix/store/wg1dachfxg6s7fhvfpqyi5ifvhwpba0q-r-dichromat-2.0-0.drv
  /nix/store/kf5svfk3a7fh8sybgc23b5kxrvxxvzp0-r-scales-0.5.0.drv
  /nix/store/rqvngyzqr1z5ri7wbh5p0pasi0i7s5cv-r-digest-0.6.15.drv
  /nix/store/7a9n3n46y8v5vknac5x96jlhl100zw51-r-ggplot2-2.2.1.drv
  /nix/store/3wr7fgjzqdk2g340997p7d1ss1cql0bm-r-productplots-0.1.1.drv
  /nix/store/f23xmlrhx2ha43cvwwqd0h6pzs23sgs1-r-purrr-0.2.4.drv
  /nix/store/mxkh44v6m30kpa5hz0gbnh7pn88yxr6g-r-tidyselect-0.2.3.drv
  /nix/store/avgnd4kabqs029jdar7lfm7fvlfqzlkm-r-BH-1.66.0-1.drv
  /nix/store/m8nji1npdv0jhpm5j4ql4pblpws8q8bp-r-bindr-0.1.drv
  /nix/store/v1bi1cqglmz2iwv7x7zxga8vkig3rrc9-r-plogr-0.1-1.drv
  /nix/store/lhhbk1xw0miwa0w5wi6hav48mqy30hl6-r-bindrcpp-0.2.drv
  /nix/store/nfip7ab3jfqq8vr1gnpvngh10jgvk8zx-r-pkgconfig-2.0.1.drv
  /nix/store/vr4dap8nyyhdw0yf1w7wss506hzagmh7-r-dplyr-0.7.4.drv
  /nix/store/a47gixcj86kw5wm5iq2b23ab96m7rh4a-r-tidyr-0.8.0.drv
  /nix/store/dqn1cjp2b1v76d1jappksdp4vizs9fx2-r-NHANES-2.1.0.drv
  /nix/store/j5fkrjhwhjgmy5867svn9iza11cxcn3b-r-gridExtra-2.3.drv
  /nix/store/5csv7l04qx4ak34cq305869l6g599868-r-data.table-1.10.4-3.drv
  /nix/store/gvr8w7wd3ykn51jvi0142sc6z4lv2bn7-r-hexbin-1.27.2.drv
  /nix/store/imi9b6pnkf4xy82hn8ficb5jlnijkxx7-r-jsonlite-1.5.drv
  /nix/store/lsl8j2k5hql79mnqm8mivl7ila2c6m3i-r-htmltools-0.3.6.drv
  /nix/store/xsxfmqip191fml7yfd27jwfg4zx5fpba-r-yaml-2.1.16.drv
  /nix/store/kilidq4gkmhvgk3kq15ivb1h3ksx5xg8-r-htmlwidgets-1.0.drv
  /nix/store/90k07cwcpz5aysxkkaf6mkfl6k8qcjrg-r-xtable-1.8-2.drv
  /nix/store/i3gygli5f3y25g4pkmp1xpbnsc401fxy-r-mime-0.5.drv
  /nix/store/nc4839zplyjg0538dhxg7ip6nizkwm1q-r-httpuv-1.3.5.drv
  /nix/store/vl1n0qxxlaqyd3pqb1xyl7p7cqzpwr35-r-sourcetools-0.1.6.drv
  /nix/store/amzk5fbr0w03vh0viiw76cq5kck54s2l-r-shiny-1.0.5.drv
  /nix/store/myhq9p2zv6yx4szslj2vfvyd3vqxqiys-r-crosstalk-1.0.0.drv
  /nix/store/pissir9gyr7k1kgwjxw0pi88j0gzx8i0-r-base64enc-0.1-3.drv
  /nix/store/pfhwsdmz8xdd4s843gn7sy90d6wqa0wm-r-curl-3.1.drv
  /nix/store/svccjsx01sa4a8wip2pcvskhx7y9in03-r-openssl-1.0.drv
  /nix/store/ygm70qxysa2yjxcblh6k5dda9mpb1z6p-r-httr-1.3.1.drv
  /nix/store/y9n426r5g8plxfg0zvcl003ky934vnyw-r-plotly-4.7.1.drv
  /nix/store/11fqik72p4i19wgppnv1xcqa8fxcdj9r-r-ggmosaic-0.1.2.drv
  /nix/store/si8ilifiz5z8wcvvy8azsfij17a0rqkf-ocaml4.04.2-batteries-2.8.0.drv
  /nix/store/6ww7y7yy69av80xk0xi9dndph4c23kpp-obandit-0.2.1.drv
  /nix/store/59cdgakgiav13d8hahrb8r26l8s2s3wj-ocs-0.2.drv
  /nix/store/w2nhj76qyqingjs7ha42sqmaz52zijq5-source.drv
  /nix/store/9y6y9dixnnza3b9nmk7l8l5z63c58c6v-zymake.drv
  /nix/store/hzaas6k7pgrhka9xbp7dagcsvwnhpzmn-r-lubridate-1.7.2.drv
  /nix/store/zwpvfj245qpjjrysgqki8j38pxslvb0n-r-docopt-0.4.5.drv
building '/nix/store/si8ilifiz5z8wcvvy8azsfij17a0rqkf-ocaml4.04.2-batteries-2.8.0.drv'...
unpacking sources
unpacking source archive /nix/store/b9bpchmcri6mnlvp54sscysbgc2bg9w4-source
source root is source
patching sources
configuring
building
build flags: SHELL=/nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin/bash
Build mode: shared
ocamlbuild -no-links -use-ocamlfind src/batteries.cma src/batteriesHelp.cmo src/batteriesThread.cma META src/batteries.cmxs src/batteriesThread.cmxs
ocamlfind ocamlopt unix.cmxa -I /nix/store/y0rm56byk5bwfgss7sf0knjmdrlpa36y-ocamlbuild-0.11.0/lib/ocaml/4.04.2/site-lib/ocamlbuild /nix/store/y0rm56byk5bwfgss7sf0knjmdrlpa36y-ocamlbuild-0.11.0/lib/ocaml/4.04.2/site-lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /nix/store/y0rm56byk5bwfgss7sf0knjmdrlpa36y-ocamlbuild-0.11.0/lib/ocaml/4.04.2/site-lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
sh: 1: /tmp/nix-build-ocaml4.04.2-batteries-2.8.0.drv-0/source/_build/myocamlbuild: Permission denied
make: *** [Makefile:93: all] Error 126
builder for '/nix/store/si8ilifiz5z8wcvvy8azsfij17a0rqkf-ocaml4.04.2-batteries-2.8.0.drv' failed with exit code 2
cannot build derivation '/nix/store/59cdgakgiav13d8hahrb8r26l8s2s3wj-ocs-0.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/08v6w3pp63r283hck5am6bd49a3zxwzg-r-directlabels-2017.03.31.drv', '/nix/store/11fqik72p4i19wgppnv1xcqa8fxcdj9r-r-ggmosaic-0.1.2.drv', '/nix/store/59cdgakgiav13d8hahrb8r26l8s2s3wj-ocs-0.2.drv', '/nix/store/7a9n3n46y8v5vknac5x96jlhl100zw51-r-ggplot2-2.2.1.drv', '/nix/store/9y6y9dixnnza3b9nmk7l8l5z63c58c6v-zymake.drv', '/nix/store/hzaas6k7pgrhka9xbp7dagcsvwnhpzmn-r-lubridate-1.7.2.drv', '/nix/store/vr4dap8nyyhdw0yf1w7wss506hzagmh7-r-dplyr-0.7.4.drv', '/nix/store/zwpvfj245qpjjrysgqki8j38pxslvb0n-r-docopt-0.4.5.drv' failed
```

**Comment by freuk** [comment]
The latest commit to master should include the pinning, you shouldn't
have to pass the nixpkgs variable to nix-shell. The nix store is mounted
read-only, and builds don't write there directly. Although, this one
apparently tries.

Could you please pull master and try with nix-shell -A banditSelection?
Sudo rights are not needed.

Quoting Xu (2018-06-06 17:15:17)

**Comment by xulunfan** [comment]
I did what you said, but the result shows the file ' nixpkgs ' was not found .

`22:57:39[xlf@master ~/Desktop/obps-284d6d2bd3820e9c3622465cc74e817b09a7dba0]$ sudo nix-shell -A banditSelection
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/xlf/Desktop/obps-284d6d2bd3820e9c3622465cc74e817b09a7dba0/default.nix:3:24
`
If my understanding is correct, the system running according to the version specified in nixpkgs-version.json. But the system does have found the correct version.
Maybe it caused my Nix incorrect settings , but I can't find the right way to set up it on the Internet (Github,google,stackoverflow). 
Could you direct me more specifically? I am a novice in OCaml and Nix. I hope to get your help. Thanks!

**Comment by freuk** [comment]
nixpkgs-version.json specifies a pinned version. The nix install should get that exact version and build on your system. Have you sourced the correct environment variables, as the nix installer explains?

In the meantime, I pushed the simulator and zymake binaries to cachix.org for your convenience:

cachix use obps
nix-build -A ocs

cachix use datamovepkgs
nix-build -A zymake

**Comment by freuk** [comment]
Additionally, it would help if you ran nix-shell -p nix-info --run nix-info.
